require:
  - rubocop-performance
  - rubocop-rake

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5
  Exclude:
    - 'test/**/*'
    - 'vendor/**/*'

Metrics:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false

# Don't enforce documentation
Style/Documentation:
  Enabled: false

# Both double and single quotes are OK
Style/StringLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
